services:
  node:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
